### ISSUE TITLE
Bug Imbuiment

### ISSUE THREAD

**Issue by eltonbrayner** [Johncorex/OTG-Premium-Version#20]
Se um player (Elite Knight) imbuir algum item de atack no slot do set com qualquer tipo de imbuiment (strike, void, vampirism) e depois de imbuir ele trocar a arma que ta no set (que ele acabou de imbuir) por outra arma qualquer o item fica bugado dando critico e hitando muito!

Se for critico: hita muito
Se for void: a mana não desce! a cada hit ela refila full
se for vampirism: o hp refila a cada hit

Nos meus teste apenas o Knight ficou com esse bug.
Fiz com todas as demais VOC e o bug não aconteceu.
Acredito que a melhor forma de acabar com esse bug é impedindo que possa imbuir qualquer item que estiver sendo usado no SET. 
Pois quando o item é imbuido dentro da backpack não acontece esse problema

Segue a imagem abaixo:
(Observem que no exato momento subiu o meu axe, que era apenas 15)

![image](https://user-images.githubusercontent.com/18264721/78415430-04bc2600-75f8-11ea-8aa8-92d46a30d640.png)

![image](https://user-images.githubusercontent.com/18264721/78415756-4ea60b80-75fa-11ea-807a-366429eaa5b8.png)

![image](https://user-images.githubusercontent.com/18264721/78415933-6fbb2c00-75fb-11ea-849d-073d4a7fe5f0.png)

**Comment by edmararulez** [comment]
'Acredito que a melhor forma de acabar com esse bug é impedindo que possa imbuir qualquer item que estiver sendo usado no SET.'

isso que foi feito no outro git onde foi copiado... é uma solução provisoria mais funcionar.

**Comment by eltonbrayner** [comment]
> 'Acredito que a melhor forma de acabar com esse bug é impedindo que possa imbuir qualquer item que estiver sendo usado no SET.'
> 
> isso que foi feito no outro git onde foi copiado... é uma solução provisoria mais funcionar.

Inclusive no GLOBAL só é possivel imbuir fora do set.

**Comment by FakeShinoda** [comment]
É legal copiar coisa bugada né ? Da nisso. Hugs !

**Comment by dudztroyer** [comment]
Pq em vez de ajudar a arrumar vcs criam um repositório novo? Se todo mundo colaborar as coisas ficam prontas antes...

**Comment by malucooo** [comment]
> Pq em vez de ajudar a arrumar vcs criam um repositório novo? Se todo mundo colaborar as coisas ficam prontas antes...

não dá pra fazer nada lá... geral aqui é bloqueado

**Comment by malucooo** [comment]
fixado!

**Comment by gpedro** [comment]
limpei a lista, fique a vontade ;*
![image](https://user-images.githubusercontent.com/2898638/78418712-e6acf080-760c-11ea-9484-666f3c101aab.png)

**Comment by dudztroyer** [comment]
Vamo lá galera, todo mundo junto essa joça fica pronta antes!
