### ISSUE TITLE
Criaturas que não deveriam ter HP estão mostrando HP ZERADO

### ISSUE THREAD

**Issue by eltonbrayner** [Johncorex/OTG-Premium-Version#23]
A tag hidehealth não está funcionando corretamente, está mostrando a barra hp zerada das criaturas para todos os jogadores.

Atualmente está assim a situação

![image](https://user-images.githubusercontent.com/18264721/78461366-9d0ce600-769e-11ea-9082-72f5ae1d3d33.png)

como deveria ser:

![image](https://user-images.githubusercontent.com/18264721/78461369-a39b5d80-769e-11ea-905c-8ffb8e36a73b.png)

**Comment by jlcvp** [comment]
Qual versão do cliente tá utilizando? Já testou no 12.30+?

**Comment by eltonbrayner** [comment]
> Qual versão do cliente tá utilizando? Já testou no 12.30+?

Testei na 11+
Na 12.30 não testei ainda
Vou testar e devolvo aqui o resultado

**Comment by gpedro** [comment]
acho que adicionaram algum byte pra esconder ou outra flag

**Comment by jlcvp** [comment]
@eltonbrayner @gpedro 
Consegui aqui no 12.31, só preciso saber a partir de qual versão esse bug começou a acontecer pra colocar o if lá do protocol

<img width="1130" alt="Screen Shot 2020-04-17 at 10 13 13" src="https://user-images.githubusercontent.com/2317417/79592756-db4bd180-80b0-11ea-95ba-41c3b59cba50.png">

**Comment by gpedro** [comment]
vc é o bixao mesmo hein doido.

Começou na 12x inteira

Atenciosamente,
Gabriel Pedro

**Comment by gpedro** [comment]
creaturetype 5 não funcionou pra mim no 12.00

**Comment by jlcvp** [comment]
tem 2 lugares, na mesma função, o primeiro creaturetype e um que tem uns ifs pra saber se é summon e tal, tem que colocar nos 2
