### ISSUE TITLE
MoTA Extension - Teleport Exit

### ISSUE THREAD

**Issue by eltonbrayner** [Johncorex/OTG-Premium-Version#27]
Teleporta da MoTA Extension de volta está sem o Action ID (64016 - já tem o script nos movements)

![image](https://user-images.githubusercontent.com/18264721/78513702-df5c2300-7783-11ea-8b03-612c6b03709a.png)

Segue o link do local:

https://www.tibiawiki.com.br/wiki/MoTA_Extension

**Comment by QuebradaZN** [comment]
Teleports Added
