### ISSUE TITLE
Quickloot not looting gold

### ISSUE THREAD

**Issue by joao-albach** [Johncorex/OTG-Premium-Version#29]
## What

When you set a container to recive the gold category it's not being looted, event if the item is the gold pouch.

## How

Set any container to loot gold and try to loot gold from a monster.

**Comment by gpedro** [comment]
why did closed?

**Comment by jlcvp** [comment]
I will reopen this until further investigation

**Comment by joao-albach** [comment]
closed because it was my mistake, it's working as expected
