### ISSUE TITLE
Some corpses are crashing the client

### ISSUE THREAD

**Issue by joao-albach** [Johncorex/OTG-Premium-Version#31]
## Expected Behavior

When there's `remains of an elemental` or `dissolved souleater` on the screen, the game should continue to work as expected.

## Current Behavior

The client (12.00/12.31) crashes when `remains of an elemental` or `dissolved souleater` is on the screen

## Possible Solution
 
Review items.otb

## Steps to Reproduce

Using this version of OTG login with a gm and use the talkaction `/i 8966` or  `/i 12632` kill an energy elemental or souleater

**Comment by QuebradaZN** [comment]
items.otb already added, check your assets

**Comment by luisbill1** [comment]
> items.otb already added, check your assets

Amigo, também estou com esse erro, já atualizei otb, tentei de tudo, mas continua crashando o cliente.
Poderia dizer exatamente o q eu deveria fazer nos "assets" do client? Abraços, agradeço muito pela ajuda <3

Obs: Estou usando um cliente proprio já 12.31

**Comment by QuebradaZN** [comment]
https://www.youtube.com/watch?v=TNfdteHfUpk&has_verified=1

**Comment by luisbill1** [comment]
> https://www.youtube.com/watch?v=TNfdteHfUpk&has_verified=1

Eu fiz exatamente tudo que é feito nesse video, mas o problema persiste
