### ISSUE TITLE
[Gamestore] Prey Wildcards does not work

### ISSUE THREAD

**Issue by joao-albach** [Johncorex/OTG-Premium-Version#34]
## Expected Behavior

When you buy prey wildcards from the store, they should be added to players prey dialog

## Current Behavior

The coins are discounted but the Prey Wildcards are not added to the player

**Comment by joao-albach** [comment]
i did a little debugging, the bonuses are being added, but the modal is not recieving the right amount

**Comment by malucooo** [comment]
Fixed
