### ISSUE TITLE
[BUG] Char não desce encima do bueiro

### ISSUE THREAD

**Issue by luisbill1** [Johncorex/OTG-Premium-Version#43]
Boneco não desce estando encima do bueiro e nem se estiver dentro da porta também não da pra dar use nela

**Comment by QuebradaZN** [comment]
Qualquer Bueiro? Manda Posição do Bueiro e porta que testou!

**Comment by luisbill1** [comment]
> Qualquer Bueiro? Manda Posição do Bueiro e porta que testou!

São todos os bueiros e todas as portas. independente de quais são...

Obs: Uma vez eu tinha um amigo q abriu um ot e o dele tbm tinha isso, ele disse q isso foi relacionado a algum bug em relação ao quickloot. Não tenho total certeza, mas foi isso que ele disse.

Obs2: Para melhor explicar, se o char estiver encima do bueiro e clicar, ele não desce, diz que não pode usar o objeto, e a mesma coisa estando no meio da porta (que o certo era poder dar o use e ele stackar um a frente)

**Comment by QuebradaZN** [comment]
Está usando qual sistema Operacional? Quando Feito essa ação Gera alguma Log no Terminal?

**Comment by luisbill1** [comment]
> Está usando qual sistema Operacional? Quando Feito essa ação Gera alguma Log no Terminal?

Windows 10. Mas a compilação foi um sucesso, 0 problemas...
Não aparece nenhum log no terminal, apenas não desce

**Comment by luisbill1** [comment]
Obs 3: não é só encima de bueiro, também serve para itens, todos os lugares que o char estiver encima ele não consegue dar use, sendo item, porta ou bueiro

**Comment by QuebradaZN** [comment]
https://ci.appveyor.com/project/malucooo/otg-premium-version/build/job/b92y281wp5nqu0pr/artifacts Utilize esse executavel! Aguardo Respostas!

**Comment by Johncorex** [comment]
Acabei de testar na OTG e desce normal, voce poderia especificar o id do bueiro que vc se refere?

**Comment by luisbill1** [comment]
> https://ci.appveyor.com/project/malucooo/otg-premium-version/build/job/b92y281wp5nqu0pr/artifacts Utilize esse executavel! Aguardo Respostas!

Não funciona amigo, mesma coisa.

**Comment by luisbill1** [comment]
> Acabei de testar na OTG e desce normal, voce poderia especificar o id do bueiro que vc se refere?

Estranho, aqui pra mim o boneco não desce... Mas tem que fazer o teste ele estando bem encima do bueiro, no sqm do bueiro e tenta descer, ele n vai... Mesma coisa em todas portas e todos os bueiros.

**Comment by Johncorex** [comment]
Problema resolvido no commit:  test fixes
