### ISSUE TITLE
[BUG] IMBUEMENT - MANA LEECH E LIFE LEECH SÓ PEGA EM 1 BICHO DA BOX

### ISSUE THREAD

**Issue by luisbill1** [Johncorex/OTG-Premium-Version#44]
O mana leech e life leech só funcionam em 1 bicho, mesmo o char acertando magia em toda a box, só pega em apenas um o roubo de vida ou roubo de mana

**Comment by miguelshta21** [comment]
e assim como e bro assi mesmo funciona na rl
