### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by torukera** [Johncorex/OTG-Premium-Version#46]
When I try compiling on a ubuntu 16.04 with 13G, shows:

Allocation failed, server out of memory!
Decrease size of your map or compile in a 64-bit mode.
(When loading "lua scripts")

**Comment by jlcvp** [comment]
Either you are using a 32bit system or a 32bit compiler

**Comment by torukera** [comment]
I'm using a 64 system and using the tutorial from forgottenserver.

https://github.com/otland/forgottenserver/wiki/Compiling-on-Ubuntu

I need do something different?

**Comment by QuebradaZN** [comment]
> I'm using a 64 system and using the tutorial from forgottenserver.
> 
> https://github.com/otland/forgottenserver/wiki/Compiling-on-Ubuntu
> 
> I need do something different?

Nothing different, Is it really 64b?

**Comment by torukera** [comment]
Yep, i've used "getconf LONG_BIT" in terminal and shows 64b. :/

**Comment by Johncorex** [comment]
use this:
apt -y install git cmake build-essential liblua5.2-dev libgmp3-dev libmysqlclient-dev libboost-system-dev libboost-iostreams-dev libboost-filesystem-dev libpugixml-dev libcrypto++-dev libspdlog-dev

send please print bro

**Comment by torukera** [comment]
> use this:
> apt -y install git cmake build-essential liblua5.2-dev libgmp3-dev libmysqlclient-dev libboost-system-dev libboost-iostreams-dev libboost-filesystem-dev libpugixml-dev libcrypto++-dev libspdlog-dev
> 
> send please print bro

I used this and it didn't change anything.

I've attached my "cmake .." and "./tfs".
![cmake](https://user-images.githubusercontent.com/65977429/83061937-2c49d080-a034-11ea-91d1-5c71f6ce221a.PNG)

![tfs](https://user-images.githubusercontent.com/65977429/83061940-2d7afd80-a034-11ea-83be-b69a615e6a4a.PNG)

(My compiling process works without erros)
![comp](https://user-images.githubusercontent.com/65977429/83061939-2d7afd80-a034-11ea-9372-800cdbd635c7.PNG)

**Comment by torukera** [comment]
I'm sorry for the double post.

I didn't get any solution for ubuntu 16.04. But, in ubuntu 18.04 anything works fine.

Thx for everyone who tried help me !
