### ISSUE TITLE
[ERROR-ConfigManger::load] cannot opne config.lua:No such file or directory

### ISSUE THREAD

**Issue by ghost** [Johncorex/OTG-Premium-Version#56]
tentei compilar no windows 7 com as config release x64 e deu esse error

**Comment by ghost** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/49000868/86395842-49973d80-bc77-11ea-9db7-dc2a9971c2d3.png)

**Comment by eltonbrayner** [comment]
Amigo,
Quando tiver erros do tipo que envolva um arquivo (no caso o config.lua) por favor coloca no post o arquivo.
Nesse caso eu preciso que você envie o config.lua pra saber oque ta acontecendo.

**Comment by jlcvp** [comment]
O arquivo theforgottenserver.exe tem que estar na mesma pasta do config.lua, você tá tentando rodar direto.
