### ISSUE TITLE
Relatando falta de memoria ao abrir.

### ISSUE THREAD

**Issue by ruandutrab** [Johncorex/OTG-Premium-Version#60]
`Allocation failed, server out of memory.
Decrease the size of your map or compile in 64 bits mode.
`

Estou rodando no Ubuntu, 16.04 64bits. 8gb de ram.

`              total        used        free      shared  buff/cache   available
Mem:           8285         234        7699          17         352        7790
Swap:           974           0         974
`
Obrigado.

**Comment by Johncorex** [comment]
fixado e testado
