### ISSUE TITLE
Unwrap / Wrap 

### ISSUE THREAD

**Issue by libergod** [Johncorex/OTG-Premium-Version#82]
Olá !! 

Descobri um bug na qual, ao comprar por exemplo um Mana Cask, e dar UNwrap na sua house, tudo ocorrerá bem... dai você vai se mudar de casa, e precisa dar Wrap novamente, vai funcionar... porém na hora de dar unwrap não funcionará mais. 

Ao dar look, será apresentado:

> 15:46 You see a decoration kit.
Wrap it in your own house to create a <decoration kit>.
Item ID: 26054, Action ID: 26054
Position: 32329, 32222, 7

invés de:

> 15:46 You see a decoration kit.
You bought this item in the Store.
Unwrap it in your own house to create a <great health potion cask>.
Item ID: 26054, Action ID: 28557
Position: 32330, 32222, 7

**Comment by Seitron** [comment]
Segui para arrumar nesse link 
https://github.com/Johncorex/OTG-Premium-Version/issues/54
