### ISSUE TITLE
BP de itens raros no mapa

### ISSUE THREAD

**Issue by lBaah** [Johncorex/OTG-Premium-Version#84]
Duas BPs com itens raros no mapa podem ser encontradas na posição 32685, 31990, 14 em que qualquer player tem acesso.

**Comment by Bipbop69** [comment]
haha,se olha os 'mapas' que foi pegado na otland vai encontra muita coisa legal :P

**Comment by Johncorex** [comment]
> Duas BPs com itens raros no mapa podem ser encontradas na posição 32685, 31990, 14 em que qualquer player tem acesso.

Obrigado por reportar, removi e passei um scan no mapa aqui, eu já sei quem fez isso.
