### ISSUE TITLE
Lava não queima - Lava Lurker

### ISSUE THREAD

**Issue by eltonbrayner** [Johncorex/OTG-Premium-Version#9]
Quando o player pisa sobre o tile de lava não queima.
Na imagem abaixo o personagem recebe dano do lava luker.
Mas ao andar sobre os pisos de lava não recebe nenhum dano.
![image](https://user-images.githubusercontent.com/18264721/77803062-0c5d5700-705b-11ea-934a-9ef85ff32bf8.png)

**Comment by malucooo** [comment]
Pega os ids plz!

**Comment by worthdavi** [comment]
https://github.com/Johncorex/OTG-Premium-Version/pull/13
